### ISSUE TITLE
Drop dependency on Selenium

### ISSUE THREAD

**Issue by nhoening** [SeitaBV/timely-beliefs#106]
It seems to me that selenium is only needed if the user wants to save a chart as PNG?

As it is quite a large dependency, I'd advocate we remove it from dependencies. Visualisations are not a core feature of this library. We can instead document somehow that it is to be installed for saving charts (e.g. in docs/viz.md and in the main ReadMe, where we describe making visualisations).

See also [this ticket](https://github.com/FlexMeasures/flexmeasures/pull/473), where that dependency created effort.

**Comment by Flix6x** [comment]
I thought about listing it as an optional dependency, but I'm not sure yet how that works. I have a second use case for such a solution, so this may be a good time to find out. `pyproject.toml`?

**Comment by nhoening** [comment]
I know nothing about that. Does that lead to a parameter or option when describing timely beliefs as a dependency, e.g. [plots]?
