### ISSUE TITLE
Logs overflowing with FutureWarning

### ISSUE THREAD

**Issue by Flix6x** [SeitaBV/timely-beliefs#145]
Since https://github.com/SeitaBV/timely-beliefs/pull/144, my logs are overflowing with `FutureWarning: 'sensor' field needs to be of type 'Sensor'. This constraint will be enforced in an upcoming version.` Can we tone this down a bit?

Maybe using [this](https://stackoverflow.com/questions/31953272/logging-print-message-only-once)?

**Comment by Ahmad-Wahid** [comment]
Should I work on this issue? It's quite bothering me whenever I want to read the logs during simulation.

**Comment by nhoening** [comment]
Yes but we still need a decision as there were several ideas.

It seems to me that the `DuplicateFilter` is neat: https://stackoverflow.com/a/60462619

**Comment by Flix6x** [comment]
Not so easy this. I'll be reverting https://github.com/SeitaBV/timely-beliefs/pull/144 for now, as it has become a nuisance.
