### ISSUE TITLE
Add version attribute

### ISSUE THREAD

**Issue by Flix6x** [SeitaBV/timely-beliefs#24]
This package could use a version attribute, according to https://www.python.org/dev/peps/pep-0396/

To support:

```
>>> import timely_beliefs
>>> timely_beliefs.__version__
0.1.0
```

**Comment by Flix6x** [comment]
I [read about](https://thepythonguru.com/writing-packages-in-python/#automated-inclusion-of-version-string-from-package) setting the version in the main __init__.py and having setup.py retrieve it from there. We would then still have to manually update versions, just in a different place.

Then I found [versioning](https://github.com/python-versioneer/python-versioneer#installation) (pandas also uses it), which automates further by deriving a version from git tags. I believe @nhoening has some experience with a similar feature? Want to try it out?

**Comment by nhoening** [comment]
I read the description which sounds a bit complex. Not a final opinion, though.

What about the version we use when we publish to pypi? They should also use the same version 

Am 15. September 2020 22:00:12 MESZ schrieb Felix Claessen <notifications@github.com>:
>I [read
>about](https://thepythonguru.com/writing-packages-in-python/#automated-inclusion-of-version-string-from-package)
>setting the version in the main __init__.py and having setup.py
>retrieve it from there. We would then still have to manually update
>versions, just in a different place.
>
>Then I found
>[versioning](https://github.com/python-versioneer/python-versioneer#installation)
>(pandas also uses it), which automates further by deriving a version
>from git tags. I believe @nhoening has some experience with a similar
>feature? Want to try it out?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/SeitaBV/timely-beliefs/issues/24#issuecomment-692946910

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by nhoening** [comment]
Actually, our to_pypi script shows that when we release we already use the version which setup.py knows about (currently hardcoded there) and for dev releases we use what git describe tells us. So nothing would have to be added for this to still work the same. (to_pypi can use a bit of documentation, though.

**Comment by nhoening** [comment]
@Flix6x How about using the versioning we are using in FlexMeasures now (using setuptools_scm)?

Or are you happy with the way it is now?

**Comment by Flix6x** [comment]
I am very happy with the way FlexMeasures is doing versioning.

**Comment by Flix6x** [comment]
Thanks for the work!
