### ISSUE TITLE
add_to_session fails when timezones don't match (even in name)

### ISSUE THREAD

**Issue by nhoening** [SeitaBV/timely-beliefs#65]
In my case, `event_start` and `belief_time` had "Europe/Amsterdam" and "Europe/Brussels", respectively, then this happened:

```
"DatetimeArray subtraction must have the same timezones or no timezones". More details: {'src_module': '/home/nicolas/envs/sempras/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py', 'src_linenr': 674, 'src_func': '_sub_datetime_arraylike', 'src_code': 'raise TypeError('}
```

Probably during `beliefs_data_frame.convert_index_from_belief_time_to_horizon()`.

I believe we can catch this problem with more clarity (real error message which displays the time zones) and maybe also earlier (even in `BDF.__init__`?). Not sure if it can/should be fixed.

**Comment by Flix6x** [comment]
Interesting. My first thought is that it should be possible to resolve this within timely beliefs, simply by converting both to utc before subtracting.

Can you try adjusting line 850 of `beliefs/classes.py`?

**Comment by nhoening** [comment]
You mean adjusting [line 850](https://github.com/SeitaBV/timely-beliefs/blob/main/timely_beliefs/beliefs/classes.py#L850) in the sense you mentioned - converting all times to UTC?

Doesn't look to me like `belief_horizons()` should be doing that ....

**Comment by Flix6x** [comment]
Why not?

**Comment by nhoening** [comment]
Oh yeah, the output isn't a datetime, so this seems like a proper fix indeed.

I just tried out doing a `.tz_convert("UTC")` on the datetimes before subtracting and that seems to resolve the problem.

I'll make a PR.
