### ISSUE TITLE
Drop support for Python3.7

### ISSUE THREAD

**Issue by nhoening** [SeitaBV/timely-beliefs#94]
We rely on SciPy, which from version 1.8.0 on dropped support for Python3.7.

See this line: https://github.com/scipy/scipy/blob/master/setup.py#L31

We can support to install 3.7 by pinning Scipy (and numpy) versions, like we did already for Python3.6 in the setup.py file.

But we won't support functionality anymore, as important code we rely on is moving on.

**Comment by nhoening** [comment]
@Flix6x do you remember what functionality we won't support as Scipy is moving on? I'm not sure I knew when I wrote this issue. 

At the moment, we do distinguish between Python versions like this:

```
  # scipy's setup requires minimal Python versions
    "scipy<1.6; python_version <= '3.6'",
    "scipy<1.8; python_version <= '3.7'",
    "scipy; python_version > '3.7'"
```

**Comment by nhoening** [comment]
We officially do not support Python3.7 anymore, so maybe this issue can be closed?

```
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",    
```

**Comment by Flix6x** [comment]
Agreed.
